CC		    = g++
CFLAGS		= -c -Wall
LDFLAGS		= -pthread 
SOURCES		= Consumer.cpp Mutex.cpp Producer.cpp Thread.cpp tutorial6.cpp
OBJECTS		= $(SOURCES:.cpp=.o)
TARGET		= mutex

all: $(SOURCES) $(TARGET)

$(TARGET): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

clean:
	rm -rf *.o $(OBJECTS)
